version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pm2
    versions:
    - 4.5.1
  - dependency-name: lodash-es
    versions:
    - 4.17.20
  - dependency-name: normalize-url
    versions:
    - 5.3.0
  - dependency-name: "@commitlint/cli"
    versions:
    - 11.0.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: prismjs
    versions:
    - 1.21.0
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: handlebars
    versions:
    - 4.7.6
  - dependency-name: react-youtube
    versions:
    - 7.9.0
